import { Barbershop, Service, Booking, Availability } from '@/types';

export const MOCK_SHOPS: Barbershop[] = [
  {
    id: 'mock-shop-1',
    name: 'Barbería El Padrino',
    address: 'Cra. 8 #12-34, Puerto Tejada',
    description: 'La mejor barbería del sector. Cortes clásicos y modernos.',
    phone: '3001234567',
    rating: 4.8,
    is_active: true,
    owner_id: 'mock-owner-1',
    created_at: '2024-01-01',
  },
  {
    id: 'mock-shop-2',
    name: 'The Barber Studio',
    address: 'Cl. 15 #5-20, Cali',
    description: 'Estudio de barbería premium. Experiencia única.',
    phone: '3109876543',
    rating: 4.6,
    is_active: true,
    owner_id: 'mock-owner-2',
    created_at: '2024-01-01',
  },
  {
    id: 'mock-shop-3',
    name: 'Classic Cuts Barber',
    address: 'Av. Roosevelt #30-10, Cali',
    description: 'Cortes clásicos con toque moderno.',
    phone: '3155551234',
    rating: 4.9,
    is_active: true,
    owner_id: 'mock-owner-3',
    created_at: '2024-01-01',
  },
  {
    id: 'mock-shop-4',
    name: 'Gentlemen\'s Lounge',
    address: 'Cra. 100 #18-23, Cali',
    description: 'Barbería de lujo para caballeros exigentes.',
    phone: '3204445678',
    rating: 4.7,
    is_active: true,
    owner_id: 'mock-owner-4',
    created_at: '2024-01-01',
  },
];

export const MOCK_SERVICES: Service[] = [
  { id: 'mock-svc-1', barbershop_id: 'mock-shop-1', name: 'Corte clásico', duration_minutes: 30, price: 15000, is_active: true },
  { id: 'mock-svc-2', barbershop_id: 'mock-shop-1', name: 'Corte + Barba', duration_minutes: 45, price: 25000, is_active: true },
  { id: 'mock-svc-3', barbershop_id: 'mock-shop-1', name: 'Arreglo de barba', duration_minutes: 20, price: 12000, is_active: true },
  { id: 'mock-svc-4', barbershop_id: 'mock-shop-1', name: 'Cejas', duration_minutes: 10, price: 8000, is_active: true },
];

export const MOCK_AVAILABILITY: Availability[] = [
  { id: 'mock-av-1', barbershop_id: 'mock-shop-1', day_of_week: 1, start_time: '09:00', end_time: '19:00', is_active: true },
  { id: 'mock-av-2', barbershop_id: 'mock-shop-1', day_of_week: 2, start_time: '09:00', end_time: '19:00', is_active: true },
  { id: 'mock-av-3', barbershop_id: 'mock-shop-1', day_of_week: 3, start_time: '09:00', end_time: '19:00', is_active: true },
  { id: 'mock-av-4', barbershop_id: 'mock-shop-1', day_of_week: 4, start_time: '09:00', end_time: '19:00', is_active: true },
  { id: 'mock-av-5', barbershop_id: 'mock-shop-1', day_of_week: 5, start_time: '09:00', end_time: '19:00', is_active: true },
  { id: 'mock-av-6', barbershop_id: 'mock-shop-1', day_of_week: 6, start_time: '09:00', end_time: '15:00', is_active: true },
];

const today = new Date().toISOString().split('T')[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'mock-bk-1',
    user_id: 'mock-user',
    service_id: 'mock-svc-1',
    barbershop_id: 'mock-shop-1',
    booking_date: today,
    start_time: '10:00',
    end_time: '10:30',
    status: 'confirmed',
    created_at: today,
    service: MOCK_SERVICES[0],
    barbershop: MOCK_SHOPS[0],
  },
  {
    id: 'mock-bk-2',
    user_id: 'mock-user',
    service_id: 'mock-svc-2',
    barbershop_id: 'mock-shop-2',
    booking_date: tomorrow,
    start_time: '14:30',
    end_time: '15:15',
    status: 'pending',
    created_at: today,
    service: MOCK_SERVICES[1],
    barbershop: MOCK_SHOPS[1],
  },
  {
    id: 'mock-bk-3',
    user_id: 'mock-user',
    service_id: 'mock-svc-3',
    barbershop_id: 'mock-shop-3',
    booking_date: yesterday,
    start_time: '11:00',
    end_time: '11:20',
    status: 'confirmed',
    created_at: yesterday,
    service: MOCK_SERVICES[2],
    barbershop: MOCK_SHOPS[2],
  },
  {
    id: 'mock-bk-4',
    user_id: 'mock-user',
    service_id: 'mock-svc-1',
    barbershop_id: 'mock-shop-1',
    booking_date: yesterday,
    start_time: '16:00',
    end_time: '16:30',
    status: 'cancelled',
    created_at: yesterday,
    service: MOCK_SERVICES[0],
    barbershop: MOCK_SHOPS[0],
  },
];

export const MOCK_BARBER_BOOKINGS: Booking[] = [
  {
    id: 'mock-bbk-1',
    user_id: 'mock-client-1',
    service_id: 'mock-svc-1',
    barbershop_id: 'mock-shop-1',
    booking_date: today,
    start_time: '09:00',
    end_time: '09:30',
    status: 'confirmed',
    created_at: today,
    service: MOCK_SERVICES[0],
    user: { id: 'mock-client-1', name: 'Carlos Pérez', email: 'carlos@mail.com', role: 'client', created_at: today },
  },
  {
    id: 'mock-bbk-2',
    user_id: 'mock-client-2',
    service_id: 'mock-svc-2',
    barbershop_id: 'mock-shop-1',
    booking_date: today,
    start_time: '10:00',
    end_time: '10:45',
    status: 'pending',
    created_at: today,
    service: MOCK_SERVICES[1],
    user: { id: 'mock-client-2', name: 'Andrés Gómez', email: 'andres@mail.com', role: 'client', created_at: today },
  },
  {
    id: 'mock-bbk-3',
    user_id: 'mock-client-3',
    service_id: 'mock-svc-3',
    barbershop_id: 'mock-shop-1',
    booking_date: today,
    start_time: '11:30',
    end_time: '11:50',
    status: 'pending',
    created_at: today,
    service: MOCK_SERVICES[2],
    user: { id: 'mock-client-3', name: 'Luis Martínez', email: 'luis@mail.com', role: 'client', created_at: today },
  },
  {
    id: 'mock-bbk-4',
    user_id: 'mock-client-4',
    service_id: 'mock-svc-4',
    barbershop_id: 'mock-shop-1',
    booking_date: today,
    start_time: '14:00',
    end_time: '14:30',
    status: 'confirmed',
    created_at: today,
    service: MOCK_SERVICES[0],
    user: { id: 'mock-client-4', name: 'Diego Ramírez', email: 'diego@mail.com', role: 'client', created_at: today },
  },
];
